"""
Generate setup.sh and install.sh from a leafhub.toml manifest dict.

The generated scripts follow the LeafHub v2 standard (2026-03-21) and include
all project-specific customizations declared in the manifest, so the scripts
can be regenerated at any time without losing project-specific logic.
"""

from __future__ import annotations

import re
from datetime import datetime, timezone


def _parse_python_req(req: str) -> tuple[int, int]:
    """Parse '>=3.11' or '>=3.10' into (major, minor). Defaults to (3, 10)."""
    m = re.search(r"(\d+)\.(\d+)", req)
    if m:
        return int(m.group(1)), int(m.group(2))
    return 3, 10


def generate_setup_sh(manifest: dict) -> str:
    """Generate a complete setup.sh from a manifest dict."""
    name = manifest["name"]
    bindings = manifest.get("bindings", [])
    alias = bindings[0]["alias"] if bindings else "default"
    setup = manifest.get("setup", {})
    extra_deps = setup.get("extra_deps", [])
    post_register = setup.get("post_register", [])
    doctor_cmd = setup.get("doctor_cmd")
    python_req = manifest.get("python") or ">=3.10"

    # Parse minimum Python version from requirement string (e.g. ">=3.11" -> 3, 11)
    min_major, min_minor = _parse_python_req(python_req)

    # Determine step count
    step_count = 5  # platform, python, venv, CLI registration, LeafHub
    if extra_deps:
        step_count += 1
    if post_register:
        step_count += 1

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # Build the extra steps section
    extra_steps = ""
    step_num = 6

    if extra_deps:
        deps_cmds = "\n".join(
            f'    info "Running: {dep}"\n    "$VENV_PYTHON" -m {dep}'
            for dep in extra_deps
        )
        extra_steps += f"""
section "Step {step_num} / {step_count}  —  Extra dependencies"
{deps_cmds}
    ok "Extra dependencies installed."
"""
        step_num += 1

    if post_register:
        post_cmds = "\n".join(
            f'    info "Running: {cmd}"\n    {cmd}'
            for cmd in post_register
        )
        extra_steps += f"""
section "Step {step_num} / {step_count}  —  Post-registration"
if [[ "$HEADLESS" != "true" ]] && [[ -t 0 || -e /dev/tty ]]; then
{post_cmds}
    ok "Post-registration steps complete."
else
    info "Skipped in headless mode. Run manually:"
"""
        for cmd in post_register:
            extra_steps += f'    info "  {cmd}"\n'
        extra_steps += "fi\n"

    return f'''#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
#  {name.upper()} — Setup  (macOS / Linux / WSL)
#
#  Generated by: leafhub init
#  Generated at: {now}
#  Source:        leafhub.toml
#
#  DO NOT EDIT — regenerate with: leafhub init .
#  All customizations live in leafhub.toml.
#
#  Usage:
#    chmod +x setup.sh && ./setup.sh
#
#  Options:
#    --reinstall      Delete and recreate the .venv
#    --headless       Non-interactive / CI mode; skips all prompts
#    --doctor         Run environment check only, then exit
#    --from-installer Internal flag set by install.sh
# ──────────────────────────────────────────────────────────────────────────────

PROJECT_NAME="{name}"
LEAFHUB_ALIAS="{alias}"

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
VENV_DIR="$SCRIPT_DIR/.venv"
REQUIREMENTS="$SCRIPT_DIR/requirements.txt"
BIN_DIR="$HOME/.local/bin"
PROJECT_BIN="$VENV_DIR/bin/$PROJECT_NAME"
PROJECT_LINK="$BIN_DIR/$PROJECT_NAME"
ORIGINAL_PATH="${{PATH:-}}"
PATH_PERSISTED=0

# ── Colours ───────────────────────────────────────────────────────────────────
if [[ -t 1 && -z "${{NO_COLOR:-}}" && "${{TERM:-dumb}}" != "dumb" ]]; then
    BOLD='\\033[1m'; GREEN='\\033[38;2;0;229;180m'; YELLOW='\\033[38;2;255;176;32m'
    RED='\\033[38;2;230;57;70m'; MUTED='\\033[38;2;110;120;148m'; NC='\\033[0m'
else
    BOLD='' GREEN='' YELLOW='' RED='' MUTED='' NC=''
fi

ok()      {{ echo -e "${{GREEN}}✓${{NC}}  $*"; }}
info()    {{ echo -e "${{MUTED}}·${{NC}}  $*"; }}
warn()    {{ echo -e "${{YELLOW}}!${{NC}}  $*"; }}
fail()    {{ echo -e "${{RED}}✗${{NC}}  $*" >&2; exit 1; }}
section() {{ echo ""; echo -e "${{BOLD}}── $* ──${{NC}}"; }}

# ── Argument parsing ──────────────────────────────────────────────────────────
REINSTALL=false
HEADLESS=false
DOCTOR=false
FROM_INSTALLER=false

for arg in "$@"; do
    case "$arg" in
        --reinstall)      REINSTALL=true ;;
        --headless)       HEADLESS=true ;;
        --doctor)         DOCTOR=true ;;
        --from-installer) FROM_INSTALLER=true ;;
    esac
done

# ── Shell RC detection ────────────────────────────────────────────────────────
detect_rc_file() {{
    local _shell_name
    _shell_name="$(basename "${{SHELL:-/bin/bash}}")"
    if [[ "$_shell_name" == "zsh" ]]; then
        echo "$HOME/.zshrc"
    else
        if [[ -f "$HOME/.bash_profile" ]]; then
            echo "$HOME/.bash_profile"
        else
            echo "$HOME/.bashrc"
        fi
    fi
}}

ensure_path() {{
    if [[ ":$PATH:" == *":$BIN_DIR:"* ]]; then return 0; fi
    export PATH="$BIN_DIR:$PATH"
    local rc_file
    rc_file="$(detect_rc_file)"
    local marker="# Added by $PROJECT_NAME installer"
    if [[ -f "$rc_file" ]] && grep -qF "$marker" "$rc_file" 2>/dev/null; then return 0; fi
    echo "" >> "$rc_file"
    echo "$marker" >> "$rc_file"
    echo "export PATH=\\"$BIN_DIR:\\$PATH\\"" >> "$rc_file"
    PATH_PERSISTED=1
}}

# ── Banner ────────────────────────────────────────────────────────────────────
if [[ "$FROM_INSTALLER" == "true" ]]; then
    section "Continuing $PROJECT_NAME setup"
else
    echo ""
    echo -e "${{BOLD}}$PROJECT_NAME — Setup${{NC}}"
    echo ""
fi

# ── Doctor shortcut ───────────────────────────────────────────────────────────
if [[ "$DOCTOR" == "true" ]]; then
    if command -v leafhub &>/dev/null; then
        leafhub doctor "$SCRIPT_DIR"
    else
        info "leafhub not found — running basic check"
        [[ -f "$SCRIPT_DIR/.leafhub" ]] && ok ".leafhub present" || fail ".leafhub missing"
        [[ -f "$SCRIPT_DIR/leafhub.toml" ]] && ok "leafhub.toml present" || fail "leafhub.toml missing"
    fi
    exit $?
fi

# ── Step 1: Platform ─────────────────────────────────────────────────────────
section "Step 1 / {step_count}  —  Platform"

OS="unknown"
case "$(uname -s)" in
    Darwin)           OS="macos" ;;
    Linux)
        if grep -qi microsoft /proc/version 2>/dev/null; then
            OS="wsl"
        else
            OS="linux"
        fi
        ;;
    MINGW*|MSYS*|CYGWIN*) fail "Use install.ps1 on Windows." ;;
esac
ok "Platform: $OS"

# ── Step 2: Python ────────────────────────────────────────────────────────────
section "Step 2 / {step_count}  —  Python"

PYTHON=""
for candidate in python3.13 python3.12 python3.11 python3.10 python3 python; do
    if command -v "$candidate" &>/dev/null; then
        PYTHON="$candidate"
        break
    fi
done

[[ -z "$PYTHON" ]] && fail "Python 3.10+ is required but not found."

PY_VERSION="$("$PYTHON" -c 'import sys; print(f"{{sys.version_info.major}}.{{sys.version_info.minor}}")')"
PY_MAJOR="$("$PYTHON" -c 'import sys; print(sys.version_info.major)')"
PY_MINOR="$("$PYTHON" -c 'import sys; print(sys.version_info.minor)')"
# Version check: require Python {min_major}.{min_minor}+
if [[ "$PY_MAJOR" -lt {min_major} ]] || [[ "$PY_MAJOR" -eq {min_major} && "$PY_MINOR" -lt {min_minor} ]]; then
    fail "Python {python_req} required, found $PY_VERSION."
fi
ok "Python $PY_VERSION ($PYTHON)"

# ── Step 3: Virtual environment ───────────────────────────────────────────────
section "Step 3 / {step_count}  —  Virtual environment"

VENV_PYTHON="$VENV_DIR/bin/python"
VENV_PIP="$VENV_DIR/bin/pip"

if [[ "$REINSTALL" == "true" && -d "$VENV_DIR" ]]; then
    info "Removing existing venv (--reinstall) ..."
    rm -rf "$VENV_DIR"
fi

if [[ ! -d "$VENV_DIR" ]]; then
    info "Creating virtual environment ..."
    "$PYTHON" -m venv "$VENV_DIR"
fi
ok "venv ready: $VENV_DIR"

info "Installing dependencies ..."
"$VENV_PIP" install --upgrade pip -q
"$VENV_PIP" install -e "$SCRIPT_DIR" -q
if [[ -f "$REQUIREMENTS" ]]; then
    "$VENV_PIP" install -r "$REQUIREMENTS" -q
fi
ok "Dependencies installed."

# ── Step 4: CLI registration ─────────────────────────────────────────────────
section "Step 4 / {step_count}  —  CLI registration"

ensure_path
mkdir -p "$BIN_DIR"

if [[ -f "$PROJECT_BIN" ]]; then
    ln -sf "$PROJECT_BIN" "$PROJECT_LINK"
    ok "$PROJECT_NAME registered at $PROJECT_LINK"
else
    info "$PROJECT_BIN not found — skipping CLI registration."
fi

# ── Step 5: LeafHub ──────────────────────────────────────────────────────────
section "Step 5 / {step_count}  —  LeafHub"

_leafhub_resolved=false

# Tier 1: system leafhub binary
if command -v leafhub &>/dev/null; then
    _lh_content="$(leafhub shell-helper 2>/dev/null || true)"
    if [[ -n "$_lh_content" ]]; then
        eval "$_lh_content"
        _leafhub_resolved=true
    fi
fi

# Tier 2: venv-installed leafhub (e.g. leafhub is a pip dependency)
if [[ "$_leafhub_resolved" != "true" && -x "$VENV_DIR/bin/leafhub" ]]; then
    _lh_content="$("$VENV_DIR/bin/leafhub" shell-helper 2>/dev/null || true)"
    if [[ -n "$_lh_content" ]]; then
        eval "$_lh_content"
        _leafhub_resolved=true
    fi
fi

# Tier 3: GitHub bootstrap
if [[ "$_leafhub_resolved" != "true" ]]; then
    _lh_content="$(curl -fsSL https://raw.githubusercontent.com/Rebas9512/Leafhub/main/register.sh 2>/dev/null || true)"
    if [[ -n "$_lh_content" ]]; then
        eval "$_lh_content"
        _leafhub_resolved=true
    fi
fi

if [[ "$_leafhub_resolved" == "true" ]] && type leafhub_setup_project &>/dev/null 2>&1; then
    leafhub_setup_project "$PROJECT_NAME" "$SCRIPT_DIR" "$LEAFHUB_ALIAS"
else
    warn "LeafHub not found — credentials must be set via environment variables."
fi
{extra_steps}
# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${{GREEN}}✓ $PROJECT_NAME setup complete.${{NC}}"
echo ""
if [[ "$PATH_PERSISTED" -eq 1 ]]; then
    echo -e "  ${{YELLOW}}Restart your terminal${{NC}} or run: source $(detect_rc_file)"
    echo ""
fi
echo -e "  Get started:"
echo -e "    ${{GREEN}}$PROJECT_NAME --help${{NC}}"
echo ""
'''


def generate_install_sh(manifest: dict) -> str:
    """Generate a one-liner install.sh from a manifest dict."""
    name = manifest["name"]
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # Use repo_url from manifest setup, or infer from name
    repo_url = manifest.get("setup", {}).get("repo_url", "")
    if not repo_url:
        repo_url = f"https://github.com/Rebas9512/{name.capitalize()}.git"

    return f'''#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
#  {name.upper()} — One-liner installer  (macOS / Linux / WSL)
#
#  Generated by: leafhub init
#  Generated at: {now}
#
#  Usage:
#    curl -fsSL <raw-url>/install.sh | bash
#    bash install.sh [target-directory]
# ──────────────────────────────────────────────────────────────────────────────

set -euo pipefail

PROJECT_NAME="{name}"
REPO_URL="{repo_url}"
DEFAULT_DIR="$HOME/$PROJECT_NAME"

# ── Colours ───────────────────────────────────────────────────────────────────
if [[ -t 1 && -z "${{NO_COLOR:-}}" && "${{TERM:-dumb}}" != "dumb" ]]; then
    BOLD='\\033[1m'; GREEN='\\033[38;2;0;229;180m'; YELLOW='\\033[38;2;255;176;32m'
    RED='\\033[38;2;230;57;70m'; MUTED='\\033[38;2;110;120;148m'; NC='\\033[0m'
else
    BOLD='' GREEN='' YELLOW='' RED='' MUTED='' NC=''
fi

info()    {{ echo -e "${{MUTED}}·${{NC}}  $*"; }}
ok()      {{ echo -e "${{GREEN}}✓${{NC}}  $*"; }}
fail()    {{ echo -e "${{RED}}✗${{NC}}  $*" >&2; exit 1; }}

normalise_path() {{
    case "$1" in
        ~/*) echo "$HOME/${{1#\\~/}}" ;;
        *)   echo "$1" ;;
    esac
}}

# ── Directory selection ───────────────────────────────────────────────────────
INSTALL_DIR=""
if [[ $# -ge 1 ]]; then
    INSTALL_DIR="$(normalise_path "$1")"
elif [[ -t 0 || -e /dev/tty ]]; then
    echo ""
    echo -e "${{BOLD}}$PROJECT_NAME Installer${{NC}}"
    echo ""
    read -rp "  Install directory [$DEFAULT_DIR]: " _user_dir < /dev/tty
    INSTALL_DIR="$(normalise_path "${{_user_dir:-$DEFAULT_DIR}}")"
else
    INSTALL_DIR="$DEFAULT_DIR"
fi

# ── Safety checks ────────────────────────────────────────────────────────────
if [[ -f "$INSTALL_DIR" ]]; then
    fail "$INSTALL_DIR is a file, not a directory."
fi

# ── Prerequisites ─────────────────────────────────────────────────────────────
command -v git >/dev/null 2>&1 || fail "git is required but not found. Install git first."

# ── Git clone / sync ─────────────────────────────────────────────────────────
if [[ -d "$INSTALL_DIR/.git" ]]; then
    info "Updating existing installation ..."
    git -C "$INSTALL_DIR" fetch --all -q
    git -C "$INSTALL_DIR" reset --hard origin/main -q
else
    info "Cloning $PROJECT_NAME ..."
    git clone "$REPO_URL" "$INSTALL_DIR" -q
fi
ok "Source ready: $INSTALL_DIR"

# ── Delegate to setup.sh ─────────────────────────────────────────────────────
exec bash "$INSTALL_DIR/setup.sh" --from-installer
'''
