/**
 * Built-in provider presets.
 *
 * Each preset pre-fills the "Add Provider" form.
 * Users can freely edit any field after selecting a preset.
 *
 * Fields mirror the backend ProviderCreateRequest schema:
 *   label, provider_type, api_format, base_url, default_model,
 *   auth_mode, auth_header, extra_headers
 */

export const PROVIDER_PRESETS = [
  // ── Major cloud providers ──────────────────────────────────────────────
  {
    id:            'openai',
    label:         'OpenAI',
    icon:          '🤖',
    provider_type: 'openai',
    api_format:    'openai-completions',
    base_url:      'https://api.openai.com/v1',
    default_model: 'gpt-4o-mini',
    auth_mode:     'bearer',
    auth_header:   '',
    extra_headers: {},
  },
  {
    id:            'anthropic',
    label:         'Anthropic',
    icon:          '🧠',
    provider_type: 'anthropic',
    api_format:    'anthropic-messages',
    base_url:      'https://api.anthropic.com',
    default_model: 'claude-opus-4-5',
    auth_mode:     'x-api-key',
    auth_header:   '',
    extra_headers: { 'anthropic-version': '2023-06-01' },
  },
  {
    id:            'gemini',
    label:         'Gemini',
    icon:          '✨',
    provider_type: 'custom',
    api_format:    'openai-completions',
    base_url:      'https://generativelanguage.googleapis.com/v1beta/openai',
    default_model: 'gemini-2.5-pro',
    auth_mode:     'bearer',
    auth_header:   '',
    extra_headers: {},
  },
  {
    id:            'azure',
    label:         'Azure OpenAI',
    icon:          '☁️',
    provider_type: 'custom',
    api_format:    'openai-completions',
    base_url:      'https://{resource}.openai.azure.com/openai/deployments/{deployment}',
    default_model: 'gpt-4o',
    auth_mode:     'x-api-key',
    auth_header:   'api-key',
    extra_headers: {},
  },

  // ── Frontier / reasoning models ───────────────────────────────────────
  {
    id:            'deepseek',
    label:         'DeepSeek',
    icon:          '🔍',
    provider_type: 'custom',
    api_format:    'openai-completions',
    base_url:      'https://api.deepseek.com/v1',
    default_model: 'deepseek-chat',
    auth_mode:     'bearer',
    auth_header:   '',
    extra_headers: {},
  },
  {
    id:            'xai',
    label:         'xAI / Grok',
    icon:          '𝕏',
    provider_type: 'custom',
    api_format:    'openai-completions',
    base_url:      'https://api.x.ai/v1',
    default_model: 'grok-4',
    auth_mode:     'bearer',
    auth_header:   '',
    extra_headers: {},
  },
  {
    id:            'mistral',
    label:         'Mistral',
    icon:          '🌬️',
    provider_type: 'custom',
    api_format:    'openai-completions',
    base_url:      'https://api.mistral.ai/v1',
    default_model: 'mistral-large-latest',
    auth_mode:     'bearer',
    auth_header:   '',
    extra_headers: {},
  },

  // ── Chinese providers ─────────────────────────────────────────────────
  {
    id:            'moonshot',
    label:         'Moonshot',
    icon:          '🌙',
    provider_type: 'custom',
    api_format:    'openai-completions',
    base_url:      'https://api.moonshot.ai/v1',
    default_model: 'kimi-k2.5',
    auth_mode:     'bearer',
    auth_header:   '',
    extra_headers: {},
  },
  {
    id:            'minimax',
    label:         'MiniMax',
    icon:          '🎯',
    provider_type: 'custom',
    api_format:    'anthropic-messages',
    base_url:      'https://api.minimax.io/anthropic',
    default_model: 'MiniMax-M2.7',
    auth_mode:     'bearer',
    auth_header:   '',
    extra_headers: { 'anthropic-version': '2023-06-01' },
  },
  {
    id:            'xiaomi',
    label:         'Xiaomi MiMo',
    icon:          '📱',
    provider_type: 'custom',
    api_format:    'anthropic-messages',
    base_url:      'https://api.xiaomimimo.com/anthropic',
    default_model: 'mimo-v2-flash',
    auth_mode:     'bearer',
    auth_header:   '',
    extra_headers: { 'anthropic-version': '2023-06-01' },
  },
  {
    id:            'kimi-coding',
    label:         'Kimi Coding',
    icon:          '💻',
    provider_type: 'custom',
    api_format:    'anthropic-messages',
    base_url:      'https://api.kimi.com/coding',
    default_model: 'k2p5',
    auth_mode:     'bearer',
    auth_header:   '',
    extra_headers: { 'anthropic-version': '2023-06-01' },
  },
  {
    id:            'zai',
    label:         'Z.AI / GLM',
    icon:          '🔮',
    provider_type: 'custom',
    api_format:    'openai-completions',
    base_url:      'https://api.z.ai/api/paas/v4',
    default_model: 'glm-5',
    auth_mode:     'bearer',
    auth_header:   '',
    extra_headers: {},
  },
  {
    id:            'doubao',
    label:         'Doubao',
    icon:          '🫘',
    provider_type: 'custom',
    api_format:    'openai-completions',
    base_url:      'https://ark.cn-beijing.volces.com/api/v3',
    default_model: 'doubao-seed-1-8-251228',
    auth_mode:     'bearer',
    auth_header:   '',
    extra_headers: {},
  },
  {
    id:            'qianfan',
    label:         'Qianfan (Baidu)',
    icon:          '🌊',
    provider_type: 'custom',
    api_format:    'openai-completions',
    base_url:      'https://qianfan.baidubce.com/v2',
    default_model: 'deepseek-v3.2',
    auth_mode:     'bearer',
    auth_header:   '',
    extra_headers: {},
  },
  {
    id:            'nvidia',
    label:         'NVIDIA NIM',
    icon:          '🟢',
    provider_type: 'custom',
    api_format:    'openai-completions',
    base_url:      'https://integrate.api.nvidia.com/v1',
    default_model: 'nvidia/llama-3.1-nemotron-70b-instruct',
    auth_mode:     'bearer',
    auth_header:   '',
    extra_headers: {},
  },

  // ── Aggregators / gateways ────────────────────────────────────────────
  {
    id:            'openrouter',
    label:         'OpenRouter',
    icon:          '🔀',
    provider_type: 'custom',
    api_format:    'openai-completions',
    base_url:      'https://openrouter.ai/api/v1',
    default_model: 'openai/gpt-4o-mini',
    auth_mode:     'bearer',
    auth_header:   '',
    extra_headers: {},
  },
  {
    id:            'together',
    label:         'Together AI',
    icon:          '🤝',
    provider_type: 'custom',
    api_format:    'openai-completions',
    base_url:      'https://api.together.xyz/v1',
    default_model: 'meta-llama/Llama-3.3-70B-Instruct-Turbo',
    auth_mode:     'bearer',
    auth_header:   '',
    extra_headers: {},
  },
  {
    id:            'huggingface',
    label:         'Hugging Face',
    icon:          '🤗',
    provider_type: 'custom',
    api_format:    'openai-completions',
    base_url:      'https://router.huggingface.co/v1',
    default_model: 'deepseek-ai/DeepSeek-R1',
    auth_mode:     'bearer',
    auth_header:   '',
    extra_headers: {},
  },

  // ── Self-hosted ───────────────────────────────────────────────────────
  {
    id:            'ollama',
    label:         'Ollama',
    icon:          '🦙',
    provider_type: 'ollama',
    api_format:    'ollama',
    base_url:      'http://localhost:11434/v1',
    default_model: 'llama3.2',
    auth_mode:     'none',
    auth_header:   '',
    extra_headers: {},
  },
  {
    id:            'vllm',
    label:         'vLLM',
    icon:          '⚡',
    provider_type: 'custom',
    api_format:    'openai-completions',
    base_url:      'http://127.0.0.1:8000/v1',
    default_model: '',
    auth_mode:     'bearer',
    auth_header:   '',
    extra_headers: {},
  },
  {
    id:            'litellm',
    label:         'LiteLLM',
    icon:          '🪶',
    provider_type: 'custom',
    api_format:    'openai-completions',
    base_url:      'http://localhost:4000',
    default_model: '',
    auth_mode:     'bearer',
    auth_header:   '',
    extra_headers: {},
  },

  // ── Custom ────────────────────────────────────────────────────────────
  {
    id:            'custom',
    label:         'Custom',
    icon:          '⚙️',
    provider_type: 'custom',
    api_format:    'openai-completions',
    base_url:      '',
    default_model: '',
    auth_mode:     'bearer',
    auth_header:   '',
    extra_headers: {},
  },
]
