"""
Tests for Phase 2 CLI commands: init, doctor, register manifest mode.

These tests validate the new commands without requiring a running LeafHub vault.
"""

from __future__ import annotations

import json
import subprocess
import sys
import textwrap
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

# Ensure src/ is importable
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "sdk-pkg"))


# ── Scaffold generator tests ────────────────────────────────────────────────


class TestGenerateSetupSh:
    def _manifest(self, **overrides) -> dict:
        base = {
            "name": "test-project",
            "python": ">=3.11",
            "bindings": [
                {"alias": "llm", "required": True, "env_prefix": "LLM",
                 "capabilities": ["chat"]},
            ],
            "setup": {
                "extra_deps": [],
                "post_register": [],
                "doctor_cmd": None,
            },
            "env_fallbacks": {},
        }
        base.update(overrides)
        return base

    def test_basic_generation(self):
        from leafhub.scaffold import generate_setup_sh

        result = generate_setup_sh(self._manifest())
        assert 'PROJECT_NAME="test-project"' in result
        assert 'LEAFHUB_ALIAS="llm"' in result
        assert "#!/usr/bin/env bash" in result
        assert "Generated by: leafhub init" in result

    def test_python_version_check_311(self):
        from leafhub.scaffold import generate_setup_sh

        result = generate_setup_sh(self._manifest(python=">=3.11"))
        assert 'PY_MINOR" -lt 11' in result
        assert "Python >=3.11 required" in result

    def test_python_version_check_312(self):
        from leafhub.scaffold import generate_setup_sh

        result = generate_setup_sh(self._manifest(python=">=3.12"))
        assert 'PY_MINOR" -lt 12' in result

    def test_python_none_defaults_to_310(self):
        from leafhub.scaffold import generate_setup_sh

        result = generate_setup_sh(self._manifest(python=None))
        assert 'PY_MINOR" -lt 10' in result

    def test_extra_deps_step(self):
        from leafhub.scaffold import generate_setup_sh

        m = self._manifest()
        m["setup"]["extra_deps"] = ["playwright install chromium"]
        result = generate_setup_sh(m)
        assert "playwright install chromium" in result
        assert "Extra dependencies" in result
        # Step count should be 6 (5 base + 1 extra)
        assert "Step 1 / 6" in result

    def test_post_register_step(self):
        from leafhub.scaffold import generate_setup_sh

        m = self._manifest()
        m["setup"]["post_register"] = ["python -m download_models"]
        result = generate_setup_sh(m)
        assert "python -m download_models" in result
        assert "Post-registration" in result

    def test_both_extra_steps(self):
        from leafhub.scaffold import generate_setup_sh

        m = self._manifest()
        m["setup"]["extra_deps"] = ["dep1"]
        m["setup"]["post_register"] = ["cmd1"]
        result = generate_setup_sh(m)
        # 5 base + 1 extra_deps + 1 post_register = 7
        assert "Step 1 / 7" in result

    def test_no_bindings_uses_default_alias(self):
        from leafhub.scaffold import generate_setup_sh

        m = self._manifest(bindings=[])
        result = generate_setup_sh(m)
        assert 'LEAFHUB_ALIAS="default"' in result

    def test_doctor_shortcut_delegates_to_leafhub(self):
        from leafhub.scaffold import generate_setup_sh

        result = generate_setup_sh(self._manifest())
        assert "leafhub doctor" in result

    def test_four_tier_leafhub_resolution(self):
        from leafhub.scaffold import generate_setup_sh

        result = generate_setup_sh(self._manifest())
        assert "Tier 1" in result or "system leafhub binary" in result
        assert "Tier 2" in result or "venv-installed leafhub" in result
        assert "Tier 3" in result or "distributed copy" in result
        assert "Tier 4" in result or "GitHub bootstrap" in result


class TestGenerateInstallSh:
    def test_basic_generation(self):
        from leafhub.scaffold import generate_install_sh

        m = {"name": "myapp", "setup": {}}
        result = generate_install_sh(m)
        assert 'PROJECT_NAME="myapp"' in result
        assert "#!/usr/bin/env bash" in result
        assert "exec bash" in result
        assert "setup.sh" in result

    def test_custom_repo_url(self):
        from leafhub.scaffold import generate_install_sh

        m = {"name": "myapp", "setup": {"repo_url": "https://github.com/user/repo.git"}}
        result = generate_install_sh(m)
        assert "https://github.com/user/repo.git" in result


class TestParseReq:
    def test_parse_common_versions(self):
        from leafhub.scaffold.generators import _parse_python_req

        assert _parse_python_req(">=3.10") == (3, 10)
        assert _parse_python_req(">=3.11") == (3, 11)
        assert _parse_python_req(">=3.12") == (3, 12)

    def test_parse_no_match_defaults(self):
        from leafhub.scaffold.generators import _parse_python_req

        assert _parse_python_req("latest") == (3, 10)
        assert _parse_python_req("") == (3, 10)


# ── _load_manifest_for_cli tests ─────────────────────────────────────────────


class TestLoadManifestForCli:
    def _write_toml(self, tmp_path: Path, content: str) -> Path:
        p = tmp_path / "leafhub.toml"
        p.write_text(textwrap.dedent(content), encoding="utf-8")
        return p

    def test_load_minimal(self, tmp_path: Path):
        from leafhub.cli import _load_manifest_for_cli

        self._write_toml(tmp_path, """
            [project]
            name = "testapp"

            [[bindings]]
            alias = "ai"
            required = true
        """)
        m = _load_manifest_for_cli(tmp_path / "leafhub.toml")
        assert m["name"] == "testapp"
        assert len(m["bindings"]) == 1
        assert m["bindings"][0]["alias"] == "ai"
        assert m["bindings"][0]["required"] is True

    def test_load_full(self, tmp_path: Path):
        from leafhub.cli import _load_manifest_for_cli

        self._write_toml(tmp_path, """
            [project]
            name = "fullapp"
            python = ">=3.12"

            [[bindings]]
            alias = "rewrite"
            required = true
            env_prefix = "REWRITE"
            capabilities = ["chat"]

            [setup]
            extra_deps = ["playwright install chromium"]
            post_register = ["python setup.py"]
            doctor_cmd = "python check.py"

            [env_fallbacks]
            rewrite = ["REWRITE_API_KEY", "OPENAI_API_KEY"]
        """)
        m = _load_manifest_for_cli(tmp_path / "leafhub.toml")
        assert m["name"] == "fullapp"
        assert m["python"] == ">=3.12"
        assert m["bindings"][0]["env_prefix"] == "REWRITE"
        assert m["setup"]["extra_deps"] == ["playwright install chromium"]
        assert m["setup"]["doctor_cmd"] == "python check.py"
        assert m["env_fallbacks"]["rewrite"] == ["REWRITE_API_KEY", "OPENAI_API_KEY"]

    def test_missing_name_raises(self, tmp_path: Path):
        from leafhub.cli import _load_manifest_for_cli

        self._write_toml(tmp_path, """
            [project]
            python = ">=3.11"
        """)
        with pytest.raises(ValueError, match="name"):
            _load_manifest_for_cli(tmp_path / "leafhub.toml")


# ── cmd_init tests ───────────────────────────────────────────────────────────


class TestCmdInit:
    def test_init_generates_scripts(self, tmp_path: Path):
        from leafhub.cli import _build_parser

        (tmp_path / "leafhub.toml").write_text(textwrap.dedent("""
            [project]
            name = "init-test"

            [[bindings]]
            alias = "llm"
            required = true
        """), encoding="utf-8")

        parser = _build_parser()
        args = parser.parse_args(["init", str(tmp_path)])
        args.func(args)

        setup_sh = tmp_path / "setup.sh"
        install_sh = tmp_path / "install.sh"
        assert setup_sh.exists()
        assert install_sh.exists()
        assert setup_sh.stat().st_mode & 0o755

        content = setup_sh.read_text(encoding="utf-8")
        assert 'PROJECT_NAME="init-test"' in content
        assert 'LEAFHUB_ALIAS="llm"' in content

    def test_init_no_manifest_fails(self, tmp_path: Path, capsys):
        from leafhub.cli import _build_parser

        parser = _build_parser()
        args = parser.parse_args(["init", str(tmp_path)])

        with pytest.raises(SystemExit):
            args.func(args)


# ── cmd_doctor tests ─────────────────────────────────────────────────────────


class TestCmdDoctor:
    def test_doctor_no_manifest_fails(self, tmp_path: Path):
        from leafhub.cli import _build_parser

        parser = _build_parser()
        args = parser.parse_args(["doctor", str(tmp_path)])

        with pytest.raises(SystemExit) as exc_info:
            args.func(args)
        assert exc_info.value.code == 1

    def test_doctor_with_manifest_no_dotfile(self, tmp_path: Path):
        from leafhub.cli import _build_parser

        (tmp_path / "leafhub.toml").write_text(textwrap.dedent("""
            [project]
            name = "doc-test"

            [[bindings]]
            alias = "llm"
            required = true
        """), encoding="utf-8")

        parser = _build_parser()
        args = parser.parse_args(["doctor", str(tmp_path)])

        with pytest.raises(SystemExit) as exc_info:
            args.func(args)
        # Should fail because .leafhub is missing
        assert exc_info.value.code == 1


# ── cmd_register manifest mode tests ─────────────────────────────────────────


class TestCmdRegisterManifestDetection:
    def test_dot_triggers_manifest_mode(self, tmp_path: Path):
        """Verify that 'register .' reads leafhub.toml."""
        from leafhub.cli import _build_parser, _load_manifest_for_cli

        (tmp_path / "leafhub.toml").write_text(textwrap.dedent("""
            [project]
            name = "manifest-reg"

            [[bindings]]
            alias = "ai"
            required = true
        """), encoding="utf-8")

        parser = _build_parser()
        args = parser.parse_args(["register", ".", "--path", str(tmp_path), "--headless"])

        # We can't actually run cmd_register without a vault,
        # but we can verify the manifest would be loaded
        raw_name = args.project_name
        assert raw_name == "."

        manifest_file = tmp_path / "leafhub.toml"
        assert manifest_file.is_file()
        m = _load_manifest_for_cli(manifest_file)
        assert m["name"] == "manifest-reg"
        assert m["bindings"][0]["alias"] == "ai"

    def test_bare_name_does_not_trigger_manifest(self, tmp_path: Path):
        """A bare name like 'myapp' should NOT trigger manifest mode
        even if a directory named 'myapp' exists with leafhub.toml."""
        from leafhub.cli import _build_parser

        # Create a directory that matches the project name
        app_dir = tmp_path / "myapp"
        app_dir.mkdir()
        (app_dir / "leafhub.toml").write_text(
            '[project]\nname = "sneaky"\n', encoding="utf-8"
        )

        parser = _build_parser()
        args = parser.parse_args(["register", "myapp", "--headless"])
        # project_name should stay as "myapp", not switch to manifest mode
        assert args.project_name == "myapp"
